site_name: "Karpav.ai"
site_description: "A knowledge hub for training, stewardship, and authentic contributions."
site_author: "Vasudev Narayanan"
site_url: "https://karpavai.github.io/"

theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: blue
    accent: grey
  font:
    text: Verdana
    code: Courier New
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_url_format: "{slug}"
      categories: true
      authors: true
  - tags

nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - Process | SOP Handbook: blog/process_sop.md
      - Paper | Unreachable Citizens:  blog/unreachable_citizens.md
  - 404: 404.md
